.PHONY : init clean update deploy

GIT_HASH := $(shell git rev-parse --short HEAD)
GIT_BRANCH := $(shell git rev-parse --abbrev-ref HEAD)
IMAGE_NAME := "codewarriorz/backend"

default:
	echo "default"

clean:
	echo "clean"

update:
	echo "update"

deploy:
	echo "deploy"
