export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const REFRESH_COUNTER = 'REFRESH_COUNTER';
export const COUNTER_REFRESHED = 'COUNTER_REFRESHED';
