export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const INCREMENT_COUNTER_IF_ODD = 'INCREMENT_COUNTER_IF_ODD';
export const REFRESH_COUNTER = 'REFRESH_COUNTER';
export const COUNTER_REFRESHED = 'COUNTER_REFRESHED';
// User
export const REGISTER_USER = 'REGISTER_USER';
export const USER_REGISTERED = 'USER_REGISTERED';
export const REMOVE_USER = 'REMOVE_USER';
export const USER_REMOVED = 'USER_REMOVED';
export const LOGIN_USER = 'LOGIN_USER';
export const USER_LOGGEDIN = 'USER_LOGGEDIN';
export const LOGOUT_USER = 'LOGOUT_USER';
export const USER_LOGGEDOUT = 'USER_LOGGEDOUT';
// Players
export const FETCH_PLAYERS = 'FETCH_PLAYERS';
export const PLAYERS_FETCHED = 'PLAYERS_FETCHED';
export const SEARCH_PLAYERS= 'SEARCH_PLAYERS'
        // should dispatch PLAYERS_FETCHED on search result
export const CREATE_NEW_PLAYER = 'CREATE_NEW_PLAYER'
export const CREATING_NEW_PLAYER = 'CREATING_NEW_PLAYER'
export const SAVE_NEW_PLAYER = 'SAVE_NEW_PLAYER'
export const NEW_PLAYER_SAVED = 'NEW_PLAYER_SAVED'
export const CANCEL_CREATE_NEW_PLAYER = 'CANCEL_CREATE_NEW_PLAYER'
export const SELECT_PLAYER= 'SELECT_PLAYER'
export const PLAYER_SELECTED= 'PLAYER_SELECTED'
export const PLAYERLIST_LOADED= 'PLAYERLIST_LOADED'
// Auth Check
export const CHECK_USER_AUTHENTICATED = 'CHECK_USER_AUTHENTICATED'
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED'
export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED'
// Orgs
export const FETCH_ORGANIZATIONS = 'FETCH_ORGANIZATIONS'
export const ORGANIZATIONS_FETCHED = 'ORGANIZATIONS_FETCHED'
export const SELECT_ORGANIZATION = 'SELECT_ORGANIZATION'
export const ORGANIZATION_SELECTED = 'ORGANIZATION_SELECTED'
export const GOTO_ORGANIZATION_SELECT = 'GOTO_ORGANIZATION_SELECT'
export const CREATE_NEW_ORGANIZATION = 'CREATE_NEW_ORGANIZATION'
export const CANCEL_CREATE_NEW_ORGANIZATION = 'CANCEL_CREATE_NEW_ORGANIZATION'
export const CREATING_NEW_ORGANIZATION = 'CREATING_NEW_ORGANIZATION'
export const SAVE_NEW_ORGANIZATION = 'SAVE_NEW_ORGANIZATION'
export const NEW_ORGANIZATION_SAVED = 'NEW_ORGANIZATION_SAVED'
// Games
export const FETCH_GAMES = 'FETCH_GAMES'
export const GAMES_FETCHED = 'GAMES_FETCHED'
export const SELECT_GAME = 'SELECT_GAME'
export const GAME_SELECTED = 'GAME_SELECTED'
export const GOTO_GAME_SELECT = 'GOTO_GAME_SELECT'
export const CREATE_NEW_GAME = 'CREATE_NEW_GAME'
export const CREATING_NEW_GAME = 'CREATING_NEW_GAME'
export const SAVE_NEW_GAME = 'SAVE_NEW_GAME'
export const NEW_GAME_SAVED = 'NEW_GAME_SAVED'
export const CANCEL_CREATE_NEW_GAME = 'CANCEL_CREATE_NEW_GAME'
// Characters
export const SELECT_CHARACTER = 'SELECT_CHARACTER'
export const CHARACTER_SELECTED = 'CHARACTER_SELECTED'
// ITEMS
export const FETCH_ITEMS = 'FETCH_ITEMS';
export const ITEMS_FETCHED = 'ITEMS_FETCHED';
export const SEARCH_ITEMS= 'SEARCH_ITEMS'
export const CREATE_NEW_ITEM = 'CREATE_NEW_ITEM'
export const CREATING_NEW_ITEM = 'CREATING_NEW_ITEM'
export const SAVE_NEW_ITEM = 'SAVE_NEW_ITEM'
export const NEW_ITEM_SAVED = 'NEW_ITEM_SAVED'
export const CANCEL_CREATE_NEW_ITEM = 'CANCEL_CREATE_NEW_ITEM'
export const SELECT_ITEM= 'SELECT_ITEM'
export const ITEM_SELECTED= 'ITEM_SELECTED'
export const ITEM_LIST_LOADED= 'ITEM_LIST_LOADED'
